export default [
    "african",
    "airedale",
    "akita",
    "appenzeller",
    "affenpinscher",
    "australian kelpie",
    "australian shepherd",
    "indian bakharwal",
    "basenji",
    "beagle",
    "bluetick",
    "borzoi",
    "bouvier",
    "boxer",
    "brabancon",
    "briard",
    "norwegian buhund",
    "boston bulldog",
    "english bulldog",
    "french bulldog",
    "staffordshire bullterrier",
    "australian cattledog",
    "cavapoo",
    "chihuahua",
    "indian chippiparai",
    "chow",
    "clumber",
    "cockapoo",
    "border collie",
    "coonhound",
    "cardigan corgi",
    "cotondetulear",
    "dachshund",
    "dalmatian",
    "great dane",
    "swedish danish",
    "scottish deerhound",
    "dhole",
    "dingo",
    "doberman",
    "norwegian elkhound",
    "entlebucher",
    "eskimo",
    "lapphund finnish",
    "bichon frise",
    "indian gaddi",
    "germanshepherd",
    "indian greyhound",
    "italian greyhound",
    "groenendael",
    "havanese",
    "afghan hound",
    "basset hound",
    "blood hound",
    "english hound",
    "ibizan hound",
    "plott hound",
    "walker hound",
    "husky",
    "keeshond",
    "kelpie",
    "kombai",
    "komondor",
    "kuvasz",
    "labradoodle",
    "labrador",
    "leonberg",
    "lhasa",
    "malamute",
    "malinois",
    "maltese",
    "bull mastiff",
    "english mastiff",
    "indian mastiff",
    "tibetan mastiff",
    "mexicanhairless",
    "mix",
    "bernese mountain",
    "swiss mountain",
    "indian mudhol",
    "newfoundland"
];
